USE [master]
GO

/****** Object:  Database [Deloitte]    Script Date: 08/10/2022 12:40:49 ******/
CREATE DATABASE [Deloitte]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Deloitte', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Deloitte.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Deloitte_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Deloitte_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Deloitte].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Deloitte] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Deloitte] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Deloitte] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Deloitte] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Deloitte] SET ARITHABORT OFF 
GO

ALTER DATABASE [Deloitte] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Deloitte] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Deloitte] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Deloitte] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Deloitte] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Deloitte] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Deloitte] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Deloitte] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Deloitte] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Deloitte] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Deloitte] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Deloitte] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Deloitte] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Deloitte] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Deloitte] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Deloitte] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Deloitte] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Deloitte] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Deloitte] SET  MULTI_USER 
GO

ALTER DATABASE [Deloitte] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Deloitte] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Deloitte] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Deloitte] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Deloitte] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Deloitte] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Deloitte] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Deloitte] SET  READ_WRITE 
GO


